# Generated by Django 4.1 on 2023-01-12 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='department_id',
            new_name='listItem',
        ),
    ]
