# Generated by Django 4.1 on 2023-01-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_department_id_listitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='image',
            field=models.ImageField(default=None, upload_to='img'),
        ),
    ]
