# Generated by Django 4.1 on 2023-01-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_listitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutme', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='listitem',
            name='image',
        ),
    ]
